## conda requirements for all packages needed to run the scanpy tutorials
# install with:  conda env create -n sibRNA2020 -f environment.yml
# then run: source activate sibRNA2020
name: sibRNA2020

channels:
 - bioconda
 - conda-forge
 - defaults
 - anaconda
 - rdonnelly
 
dependencies:
 - r-base=3.5
# - rstudio=1.1.456
 - rstudio=1.2.502
 - bioconductor-biomart=2.38
 - bioconductor-destiny
 - r-devtools=2.1.0
 - r-biocmanager=1.30
 - r-data.table=1.11
 - r-apcluster
 - r-dplyr=0.8
 - r-igraph=1.2
 - r-pheatmap=1.0
 - r-rafalib=1.0
 - r-rcolorbrewer=1.1
 - r-scales=1.0
 - r-seurat=3.0.1
 - r-umap=0.2
 - umap-learn=0.3.7
 - r-grr=0.9.5
 - r-hdf5r=1.2.0
 - louvain
 - leidenalg
 - r-bookdown
 - r-venn=1.7
 - wget=1.19.4  # For compatibility with genomeinfodbdata (currently broken)
 - r-venn
 - libgfortran